package com.zenhomes.energyconsumption.controllers;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.zenhomes.energyconsumption.models.CounterConsumption;
import com.zenhomes.energyconsumption.repositories.AbstractRepositoryTest;
import com.zenhomes.energyconsumption.repositories.CounterConsumptionRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.web.server.LocalServerPort;
import org.springframework.core.io.ClassPathResource;

import java.io.IOException;
import java.nio.file.Files;

import static org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class CounterConsumptionControllerEndToEndTest extends AbstractRepositoryTest {

    @LocalServerPort
    private int serverPort;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private TestRestTemplate testRestTemplate;

    @Autowired
    private CounterConsumptionRepository counterConsumptionRepository;

    @Test
    void shouldSaveCounterInformation() throws Exception {
        testRestTemplate.postForObject(getBaseUrl() + "counter_callback",
                objectMapper.readTree(readTestResource("counter_callback_request.json")), Void.class);

        final var firstSavedCounterConsumption = counterConsumptionRepository.findAll().get(0);
        final var expectedCounterConsumption = new CounterConsumption("1", 10000.123);
        assertTrue(reflectionEquals(firstSavedCounterConsumption, expectedCounterConsumption, AUTOGENERATED_FIELDS));
    }

    private byte[] readTestResource(String resourceLocation) throws IOException {
        return Files.readAllBytes(new ClassPathResource(resourceLocation).getFile().toPath());
    }

    private String getBaseUrl() {
        return "http://localhost:" + serverPort + "/";
    }
}