package com.zenhomes.energyconsumption.repositories;

import com.zenhomes.energyconsumption.configuration.MongoConfiguration;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Query;

@Import(MongoConfiguration.class)
public abstract class AbstractRepositoryTest {

    protected static final String[] AUTOGENERATED_FIELDS = new String[]{"id", "createdAt"};

    @Autowired
    protected MongoTemplate mongoTemplate;

    @BeforeEach
    void setUp() {
        this.mongoTemplate.getCollectionNames().forEach((collection) -> this.mongoTemplate.remove(new Query(), collection));
    }

}