package com.zenhomes.energyconsumption.repositories;

import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Query;

public abstract class AbstractRepositoryTest {

    protected static final String[] AUTOGENERATED_FIELDS = new String[]{"id"};

    @Autowired
    private MongoTemplate mongoTemplate;

    @BeforeEach
    void setUp() {
        this.mongoTemplate.getCollectionNames().forEach((collection) -> {
            this.mongoTemplate.remove(new Query(), collection);
        });
    }

}